
pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        sh 'echo "Building PetCart Store dummy project"'
      }
    }

    stage('Test') {
      steps {
        sh 'echo "Running unit tests (dummy)"'
      }
    }

    stage('Deploy') {
      steps {
        sh 'echo "Deploying PetCart Store to dev environment (dummy)"'
      }
    }
  }
}
