apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcart-deployment
  namespace: petcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petcart
  template:
    metadata:
      labels:
        app: petcart
    spec:
      containers:
        - name: petcart
          image: ${IMAGE_URI}
          ports:
            - containerPort: 80
