apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: petcart-eks
  region: us-east-1
  tags:
    project: petcart
    environment: demo
    managed-by: eksctl

iam:
  withOIDC: true

managedNodeGroups:
  - name: petcart-ng
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
